apiVersion: v1
kind: Namespace
metadata:
  name: bankapp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-bankapp-aks
  namespace: bankapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: user-role
  namespace: bankapp
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-rolebinding
  namespace: bankapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user-role
subjects:
- namespace: bankapp
  kind: ServiceAccount
  name: jenkins-bankapp-aks
