apiVersion: v1
kind: Namespace
metadata:
  name: mysql
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-mysql
  namespace: mysql
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: user-role
  namespace: mysql
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-rolebinding
  namespace: mysql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user-role
subjects:
- namespace: mysql
  kind: ServiceAccount
  name: jenkins-mysql
